export const IMG = {
  // 工商信息
  BUSINESS_INFO: 'https://find-console.newgalaxyai.com/glks/assets/corpDetail/corpDetail1.png',
  // 股东信息
  SHAREHOLDER_INFO: 'https://find-console.newgalaxyai.com/glks/assets/corpDetail/corpDetail2.png',
  // 人员信息
  PERSONNEL_INFO: 'https://find-console.newgalaxyai.com/glks/assets/corpDetail/corpDetail3.png',
  // 核心人员
  CORE_PERSONNEL: 'https://find-console.newgalaxyai.com/glks/assets/corpDetail/corpDetail4.png',
  // 工商变更
  BUSINESS_CHANGE: 'https://find-console.newgalaxyai.com/glks/assets/corpDetail/corpDetail5.png',
  // 企业年报
  ENTERPRISE_REPORT: 'https://find-console.newgalaxyai.com/glks/assets/corpDetail/corpDetail6.png',
  // 对外投资
  OUTSIDE_INVESTMENT: 'https://find-console.newgalaxyai.com/glks/assets/corpDetail/corpDetail7.png',
  // 分支机构
  BRANCH_OFFICE: 'https://find-console.newgalaxyai.com/glks/assets/corpDetail/corpDetail8.png',
  // 实际控制人
  ACTUAL_CONTROLLER: 'https://find-console.newgalaxyai.com/glks/assets/corpDetail/corpDetail9.png',
  // 实际控制权
  ACTUAL_CONTROL: 'https://find-console.newgalaxyai.com/glks/assets/corpDetail/corpDetail10.png',
  // 直接控制企业
  DIRECT_CONTROL: 'https://find-console.newgalaxyai.com/glks/assets/corpDetail/corpDetail11.png',
  // 工商自主公示
  BUSINESS_PUBLICITY: 'https://find-console.newgalaxyai.com/glks/assets/corpDetail/corpDetail12.png',
  // 协同股东
  COOPERATIVE_SHAREHOLDER: 'https://find-console.newgalaxyai.com/glks/assets/corpDetail/corpDetail13.png',
  // 间接持股企业
  INDIRECT_HOLDING: 'https://find-console.newgalaxyai.com/glks/assets/corpDetail/corpDetail14.png',
  // 疑似关系
  SUSPECTED_RELATION: 'https://find-console.newgalaxyai.com/glks/assets/corpDetail/corpDetail15.png',
  // 企业产品
  ENTERPRISE_PRODUCT: 'https://find-console.newgalaxyai.com/glks/assets/corpDetail/corpDetail16.png',
  // 同业分析
  PEER_ANALYSIS: 'https://find-console.newgalaxyai.com/glks/assets/corpDetail/corpDetail17.png'
}
