export const ROUTE = {
    // 工商信息
    BUSINESS_INFO: '/subpackages/company/enterpriseDetail/detail/businessInfo/index',
    // 股东信息
    SHAREHOLDER_INFO: '/subpackages/company/enterpriseDetail/detail/shareholderInfo/index',
    // 人员信息
    PERSONNEL_INFO: '/subpackages/company/enterpriseDetail/detail/personnelInfo/index',
    // 核心人员
    CORE_PERSONNEL: '/subpackages/company/enterpriseDetail/detail/corePersonnel/index',
    // 工商变更
    BUSINESS_CHANGE: '/subpackages/company/enterpriseDetail/detail/businessChange/index',
    // 企业年报
    ENTERPRISE_REPORT: '/subpackages/company/enterpriseDetail/detail/annualReport/index',
    // 年报详情
    ANNUAL_DETAIL: '/subpackages/company/enterpriseDetail/detail/annualDetail/index',
    // 对外投资
    OUTSIDE_INVESTMENT: '/subpackages/company/enterpriseDetail/detail/foreignInvestment/index',
    // 分支机构
    BRANCH_OFFICE: '/subpackages/company/enterpriseDetail/detail/branchOffice/index',
    // 实际控制人
    ACTUAL_CONTROLLER: '/subpackages/company/enterpriseDetail/detail/actualController/index',
    // 实际控制权
    ACTUAL_CONTROL: '/subpackages/company/enterpriseDetail/detail/actualControl/index',
    // 直接控制企业
    DIRECT_CONTROL: '/subpackages/company/enterpriseDetail/detail/directControl/index',
    // 工商自主公示
    BUSINESS_PUBLICITY: '/subpackages/company/enterpriseDetail/detail/businessPublicity/index',
    // 协同股东
    COOPERATIVE_SHAREHOLDER: '/subpackages/company/enterpriseDetail/detail/cooperativeShareholder/index',
    // 间接持股企业
    INDIRECT_HOLDING: '/subpackages/company/enterpriseDetail/detail/indirectHolding/index',
    // 疑似关系
    SUSPECTED_RELATION: '/subpackages/company/enterpriseDetail/detail/suspectedRelation/index',
    // 企业产品
    ENTERPRISE_PRODUCT: '/subpackages/company/enterpriseDetail/detail/enterpriseProduct/index',
    // 同业分析
    PEER_ANALYSIS: '/subpackages/company/enterpriseDetail/detail/industryAnalysis/index',
    // 分析报告
    AI_RESEARCH_REPORT: '/subpackages/company/aiResearchReport/index',
    // 添加跟进
    ADD_FOLLOW: '/subpackages/cluePage/addFollow/index',
    // 跟进记录
    FOLLOW_RECORD: '/subpackages/cluePage/followList/index',
}

export const ROUTE_NAME = {
    // 工商信息
    BUSINESS_INFO: '工商信息',
    // 股东信息
    SHAREHOLDER_INFO: '股东信息',
    // 人员信息
    PERSONNEL_INFO: '人员信息',
    // 核心人员
    CORE_PERSONNEL: '核心人员',
    // 工商变更
    BUSINESS_CHANGE: '工商变更',
    // 企业年报
    ENTERPRISE_REPORT: '企业年报',
    // 对外投资
    OUTSIDE_INVESTMENT: '对外投资',
    // 分支机构
    BRANCH_OFFICE: '分支机构',
    // 实际控制人
    ACTUAL_CONTROLLER: '受益人',
    // 实际控制权
    ACTUAL_CONTROL: '实际控制权',
    // 直接控制企业
    DIRECT_CONTROL: '直接控制企业',
    // 工商自主公示
    BUSINESS_PUBLICITY: '工商自主公示',
    // 协同股东
    COOPERATIVE_SHAREHOLDER: '协同股东',
    // 间接持股企业
    INDIRECT_HOLDING: '间接持股企业',
    // 疑似关系
    SUSPECTED_RELATION: '疑似关系',
    // 企业产品
    ENTERPRISE_PRODUCT: '企业产品',
    // 同业分析
    PEER_ANALYSIS: '同业分析',
}

export const ROUTE_PARAMS_NAME = {
    // 统一社会信用代码
    CREDIT_CODE: 'creditCode',
    // 公司名称
    COMPANY_NAME: 'name',
    // 线索ID
    CLUE_ID: 'clueId',
    // 线索在线索列表的index
    CLUE_INDEX: 'clueIndex',
}
